apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: backend
spec:
  containers:
    - name: stress
      image: polinux/stress
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "100M", "--vm-hang", "1"]
  restartPolicy: Never
