apiVersion: v1
kind: LimitRange
metadata:
  name: backend-limits
  namespace: backend
spec:
  limits:
    - type: Container
      default:
        cpu: "100m"
        memory: "64Mi"
      defaultRequest:
        cpu: "50m"
        memory: "32Mi"
      min:
        cpu: "10m"
        memory: "16Mi"
      max:
        cpu: "200m"
        memory: "128Mi"
