apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secret-service
  template:
    metadata:
      labels:
        app: secret-service
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "echo DB_USER=$DB_USER && echo DB_PASS=$DB_PASS && ls -l /etc/tls && sleep 3600"]
