apiVersion: v1
kind: Service
metadata:
  name: internal-metrics
  namespace: frontend-dev
spec:
  selector:
    app: metrics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9100
  externalIPs:
    - 203.0.113.42
