apiVersion: v1
kind: Pod
metadata:
  name: bad-pod
  namespace: production-test
spec:
  hostPID: true                
  containers:
    - name: bad-busybox
      image: busybox:1.36
      command: ["sh", "-c", "echo Violating restricted && sleep 3600"]
      securityContext:
        runAsUser: 0            
        allowPrivilegeEscalation: true
        capabilities:
          add: ["NET_ADMIN"]  
      volumeMounts:
        - name: host-vol
          mountPath: /host     
  volumes:
    - name: host-vol
      hostPath:
        path: /etc              
