apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: message-operator-role
rules:
  - apiGroups: ["example.com"]
    resources: ["messages"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: message-operator-rolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: message-operator-role
  apiGroup: rbac.authorization.k8s.io
