apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh","-c","echo ready && sleep 3600"]
      volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
