apiVersion: v1
kind: Pod
metadata:
  name: load-pod
spec:
  containers:
    - name: stress
      image: polinux/stress
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "90M", "--vm-hang", "1"]
  restartPolicy: Never
