apiVersion: v1
kind: Pod
metadata:
  name: memory-app
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args: ["--vm","1","--vm-bytes","300M","--vm-hang","1"]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
